### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gatotta69** [NikitaFoxze/Offensive-Core#1]
![ssdsdsdsd](https://github.com/user-attachments/assets/fe7fadd6-088a-4937-bf8e-ab6e0954714d)
in which part is this error? I haven’t even changed anything in the script yet. I also can't enter any mode

**Comment by NikitaFoxze** [comment]
Thanks for finding it, fixed it and uploaded a new one to releases. The error was in one line of code)

**Comment by gatotta69** [comment]
I have tried the RU EN and RU versions and all of them result in an AMX backtrace. Can you explain where the error is?

**Comment by gatotta69** [comment]
can I contact you via discord or telegram?

**Comment by NikitaFoxze** [comment]
It's very strange, after your discovery I re-uploaded the archive and now I download it, start playing and everything works. At what point do you get the error and send me a bigger screenshot of the console.

**Comment by gatotta69** [comment]
for me, everything works fine starting from compilation to running the server, but when I login and choose the tdm or DM menu, nothing happens and an AMX backtrace appears
some commands, like /leave, also trigger the AMX backtrace log

**Comment by NikitaFoxze** [comment]
That's why one error with the player entering the mode was fixed and I re-uploaded the archive to the releases. Try downloading the archive again and entering any mode.
